//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSArray, NSDictionary, NSNumber, NSString;

@interface PlayerDataItem : NSObject



@property(copy, nonatomic) NSString *sourceid; // @synthesize sourceid=_sourceid;
@property(copy, nonatomic) NSString *video_type; // @synthesize video_type=_video_type;
@property(copy, nonatomic) NSString *subjectId;
@property(retain, nonatomic) NSDictionary *loading;
@property(copy, nonatomic) NSString *loadImage;

@property(copy, nonatomic) NSString *pc; // @synthesize pc=_pc;
@property(copy, nonatomic) NSString *ctype; // @synthesize ctype=_ctype;
@property(copy, nonatomic) NSString *tvId; // @synthesize tvId=_tvId;
@property(copy, nonatomic) NSString *albumId; // @synthesize albumId=_albumId;

@end

