//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface IESAntiSpam : NSObject
{
    long long _MWIyMDgyNjM1YmRlZWY3YzFjMDAyODllYmE2ZTJiYzYgIC0K;
    long long _MWM3YjBlMDZmZmFhZGQ0NzBhNzdmOGEzODcwZDRhYzcgIC0K;
}

@property long long MWM3YjBlMDZmZmFhZGQ0NzBhNzdmOGEzODcwZDRhYzcgIC0K; 
@property long long MWIyMDgyNjM1YmRlZWY3YzFjMDAyODllYmE2ZTJiYzYgIC0K;

+ (id)sharedInstance;

+ (id)encryptDataWithTimeStamp:(long long)arg1 parameters:(id)arg2;

+(id)generalAsMas:(NSNumber*)time parameters:(id)info;

+(id)generalRequestSecurityHeader:(NSURL*)url message:(NSDictionary*)info;

- (id)testForAlert:(id)arg1 msg:(id)arg2;

@end

